version: "3.7"
services:
  php-app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: simple-transfers
    container_name: simple-transfers-app
    restart: unless-stopped
    working_dir: /var/www/html/
    volumes:
      - ./:/var/www/html
    networks:
      - simple-transfers
    depends_on:
      - db
    environment:
      CONTAINER_ROLE: app

  nginx:
    image: nginx:1.18-alpine
    container_name: simple-transfers-nginx
    restart: unless-stopped
    depends_on:
      - php-app
    ports:
      - 8000:80
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - simple-transfers

  db:
    image: mysql:8.0
    container_name: simple-transfers-db
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - 33061:3306
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - simple-transfers

networks:
  simple-transfers:
    driver: bridge

volumes:
  mysql-data:
